version: '3.8'
services:
  prometheus:
    image: prom/prometheus
    volumes:
      - ./config:/etc/prometheus
      - ./data:/prometheus
    ports:
      - 9090:9090

  node1:
    image: prom/node-exporter
    ports:
      - 8080:9100

  node2:
    image: prom/node-exporter
    ports:
      - 8081:9100

  node3:
    image: prom/node-exporter
    ports:
      - 8082:9100
